version: '3'
services:
  mysql:
    # With SB 2.4.0 = MySQL 8.0.22, see spring-boot-dependencies
    image: mysql:8.0.22
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: api
      MYSQL_USER: api
      MYSQL_PASSWORD: api
    ports:
      - 3306:3306
