spring:
  datasource:
    username: api
    password: api
    url: jdbc:mysql://localhost:3306/api?useSSL=false
  jpa:
    hibernate:
      ddl-auto: create
    properties.hibernate.dialect: org.hibernate.spatial.dialect.mysql.MySQL8SpatialDialect
